version: '3.3'

services: 
 proxy: 
  image: traefik:v1.7.18
  networks: 
   - traefik
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  ports: 
   - target: 80 
     published: 80 
     protocol: tcp 
   - 8080:8080 
   - 9090:9090 
  command:  
     -  --web
     -  --docker
     -  --docker.domain=docker.localhost
     -  --docker.swarmmode 
     -  --docker.watch
     - --defaultentrypoints="http,https"
     - --logLevel=DEBUG
  deploy: 
   replicas: 1 
   placement: 
    constraints: 
      - node.role == manager  
      - node.labels.type == master
   restart_policy: 
    condition: on-failure 

networks: 
 traefik: 
